package net.emirikol.golemancy;

import com.terraformersmc.modmenu.api.*;
import me.shedaniel.autoconfig.*;
import me.shedaniel.autoconfig.annotation.*;

import net.minecraft.text.*;
import net.minecraft.client.util.math.*;

@Config(name = "golemancy")
public class GolemancyConfig implements ConfigData,ModMenuApi {	
	public float GRAFT_SPEED_MULTIPLIER = 1.0F;
	public float GRAFT_FUEL_MULTIPLIER = 1.0F;
	public float GRAFT_POTENCY_MULTIPLIER = 1.0F;
	
	@Override
	public ConfigScreenFactory<?> getModConfigScreenFactory() {
		//Causes the config screen generated by AutoConfig to be opened when the ModMenu configuration button is clicked.
		return parent -> AutoConfig.getConfigScreen(GolemancyConfig.class, parent).get();
	}

	public static int getGraftDuration() {
		//How many ticks should a soul grafter take to graft two souls?
		GolemancyConfig config = AutoConfig.getConfigHolder(GolemancyConfig.class).getConfig();
		float adjustedGraftDuration = 2400.0F / config.GRAFT_SPEED_MULTIPLIER; //base graft duration is 2400 ticks, or 2 minutes
		int roundedGraftDuration = Math.round(adjustedGraftDuration);
		if (roundedGraftDuration < 1) {
			return 1;
		}
		return roundedGraftDuration;
	}
	
	public static int getFuelValue() {
		//How many ticks of fuel should a piece of bone meal provide?
		GolemancyConfig config = AutoConfig.getConfigHolder(GolemancyConfig.class).getConfig();
		float adjustedFuelValue = 600.0F * config.GRAFT_FUEL_MULTIPLIER; //bonemeal burns for 600 ticks, or 30 seconds
		int roundedFuelValue = Math.round(adjustedFuelValue);
		if (roundedFuelValue < 1) {
			return 1;
		}
		return roundedFuelValue;
	}
	
	public static float getPotencyMultiplier() {
		//How many soulstones should a soul grafting produce, compared to the default potency?
		GolemancyConfig config = AutoConfig.getConfigHolder(GolemancyConfig.class).getConfig();
		return config.GRAFT_POTENCY_MULTIPLIER;
	}
}